---
# file: tasks/sudo.yml

- name: Allow 'wheel' group passwordless sudo
  lineinfile: dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'
